import {test,expect,type Page} from '@playwright/test';
const password='synthetic-browser-test-password-only';
async function login(page:Page){await page.goto('/login');await page.getByLabel('이메일',{exact:true}).fill('demo@example.test');await page.getByLabel('비밀번호',{exact:true}).fill(password);await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page.getByRole('heading',{name:'내 하루와 생각',exact:true})).toBeVisible();}
test('theme preference persists and follows OS without leaking content before login',async({page})=>{
 await page.emulateMedia({colorScheme:'dark'});await page.goto('/login');await expect(page.locator('html')).toHaveAttribute('data-ieum-theme','dark');await expect(page.getByRole('navigation')).toHaveCount(0);await page.getByLabel('화면 테마').selectOption('light');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-ieum-theme','light');await page.getByLabel('화면 테마').selectOption('system');await expect(page.locator('html')).toHaveAttribute('data-ieum-theme','dark');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
});
test('records to task result to wiki, then review and publish a real document',async({page})=>{
 const stamp=Date.now();await login(page);await page.getByLabel('화면 테마').selectOption('dark');
 await page.getByRole('link',{name:'기록함',exact:true}).click();await page.getByLabel('기록 제목').fill('브라우저 기록 '+stamp);await page.getByLabel('원문',{exact:true}).fill('실제로 실행한 검증의 원본 경험입니다.');await page.getByRole('button',{name:'원본 기록 저장'}).click();await expect(page.getByRole('heading',{name:'기록 · 출처',exact:true})).toBeVisible();await page.getByRole('button',{name:'이 기록에서 할일 만들기'}).click();await expect(page.getByText('이 기록에서 할일이 만들어졌습니다.')).toBeVisible();
 await page.getByRole('link',{name:'할일',exact:true}).click();const task=page.locator('li.ieum-list-item').filter({hasText:'브라우저 기록 '+stamp});await task.getByLabel('할일 상태').selectOption('DONE');await expect(task.getByText('DONE',{exact:true}).first()).toBeVisible();await task.getByRole('button',{name:'결과 기록'}).click();await task.getByLabel('실행 결과와 새 경험').fill('행동에서 얻은 새 결과');await task.getByRole('button',{name:'결과를 기록으로 저장'}).click();await expect(task.getByLabel('실행 결과와 새 경험')).toHaveCount(0);
 await page.getByRole('link',{name:'개인 위키',exact:true}).click();await page.getByLabel('위키 제목').fill('검증 위키 '+stamp);await page.getByRole('button',{name:'작성 시작'}).click();await page.getByLabel('Markdown 본문').fill('# 검증 기록\n\n원문과 결과를 연결한 개인 지식입니다.');await expect(page.getByText(/저장됨 · v2/)).toBeVisible();
 await page.getByRole('link',{name:'문서 작업실',exact:true}).click();await page.getByLabel('문서 제목').fill('검토 문서 '+stamp);await page.getByRole('button',{name:'작성 시작'}).click();await page.getByLabel('Markdown 본문').fill('# 공개 통찰\n\n개인 원문 대신 공개하기로 검토한 해석만 제공합니다.');await expect(page.getByText(/저장됨 · v2/)).toBeVisible();await page.getByRole('button',{name:'버전 고정',exact:true}).click();await expect(page.getByText(/r1 버전이 고정/)).toBeVisible();await page.screenshot({path:'test-results/editor-dark.png',fullPage:true});
 await page.getByRole('link',{name:'이 버전 검토 →'}).click();await page.getByLabel('현재 비밀번호',{exact:true}).fill(password);await page.getByRole('button',{name:'재확인',exact:true}).click();await expect(page.getByText(/재확인되었습니다/)).toBeVisible();for(const c of await page.locator('input[type=checkbox]').all())await c.check();await page.getByRole('button',{name:'이 버전 검토 완료',exact:true}).click();await page.getByRole('button',{name:'검토한 버전 발행',exact:true}).click();await expect(page.getByText(/발행되었습니다/)).toBeVisible();
 await page.getByRole('link',{name:'발행본',exact:true}).click();await expect(page.getByText('검토 문서 '+stamp,{exact:true})).toBeVisible();await page.getByLabel('화면 테마').selectOption('light');await page.screenshot({path:'test-results/publications-light.png',fullPage:true});
});
test('private routes load at mobile size with no global horizontal overflow or JS errors',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page);await page.setViewportSize({width:390,height:844});
 for(const path of ['/app','/app/captures','/app/tasks','/app/calendar','/app/wiki','/app/contexts','/app/sources','/app/search','/app/documents','/app/proposals','/app/publications','/app/delivery','/app/assets','/app/data-transfer','/app/trash','/app/jobs','/app/audit','/app/notifications','/settings','/settings/access','/ops/users','/ops/logs','/ops/health']){await page.goto(path);await expect(page.locator('#main-content')).toBeVisible();await page.waitForTimeout(120);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),path).toBe(true);}
 expect(errors).toEqual([]);await page.screenshot({path:'test-results/mobile-dark.png',fullPage:true});
});
