import {useEffect,useState,type ReactNode,Component} from 'react';import {createBrowserRouter,RouterProvider,NavLink,Outlet,Navigate,useLocation,useNavigate} from 'react-router-dom';import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button,Card,Dialog,Field,Notice,Status} from '../../../packages/ui/src';import type {Me} from '../../../packages/contracts/src';
import {AccountContext,request,textError} from './shared/api';import {ThemeSelect,ErrorMessage} from './shared/components';import {Login,SecuritySettings} from './features/account';
import {Dashboard,Captures,CaptureDetail,Contexts,Tasks,Calendar,Sources,Search,Proposals} from './features/personal';import {DocumentList,DocumentEditor,PublishReview,Publications,Delivery} from './features/documents';import {Assets,DataTransfer,Trash,Jobs,Audit,Notifications,Users,OperatorLogs,Health,Access} from './features/operations';
const links=[['/app','내 하루와 생각'],['/app/captures','기록함'],['/app/tasks','할일'],['/app/calendar','일정'],['/app/wiki','개인 위키'],['/app/contexts','맥락 · 프로젝트'],['/app/sources','외부 자료'],['/app/search','통합 검색'],['/app/documents','문서 작업실'],['/app/proposals','정리 제안함'],['/app/publications','발행본'],['/app/delivery','Delivery API'],['/app/assets','파일 · 자료'],['/app/data-transfer','가져오기 · 내보내기'],['/app/trash','휴지통'],['/app/jobs','작업 상태'],['/app/audit','내 변경 이력'],['/app/notifications','알림'],['/settings','설정 · 보안'],['/settings/access','권한 경계']];
export class ErrorBoundary extends Component<{children:ReactNode},{error:Error|null}>{override state={error:null as Error|null};static getDerivedStateFromError(error:Error){return {error};}override render(){return this.state.error?<div className="ieum-main"><Notice tone="danger">화면을 표시하지 못했습니다. 저장된 자료는 유지됩니다.</Notice><Button onClick={()=>location.reload()}>다시 불러오기</Button></div>:this.props.children;}}
function Shell(){const me=useQuery({queryKey:['me'],queryFn:()=>request<Me>('/api/v1/me'),retry:false,refetchOnWindowFocus:false,staleTime:60000}),q=useQueryClient(),navigate=useNavigate(),loc=useLocation(),[navOpen,setNavOpen]=useState(false),[logoutError,setLogoutError]=useState<unknown>(null),[reauthOpen,setReauthOpen]=useState(false),[password,setPassword]=useState('');
 useEffect(()=>{setNavOpen(false);document.getElementById('main-content')?.focus();},[loc.pathname]);
 useEffect(()=>{let last=0;const activity=()=>{if(Date.now()-last>60000){last=Date.now();void request('/api/v1/me/activity',{method:'POST',body:{}}).catch(()=>{});}};window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);return()=>{window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);};},[]);
 if(me.isPending)return <div className="ieum-main"><Notice>개인 공간을 확인하는 중…</Notice></div>;if(!me.data)return <Navigate to="/login" replace/>;
 if(me.data.requiresMfa&&loc.pathname!=='/settings')return <Navigate to="/settings" replace/>;
 const shownLinks=me.data.requiresMfa?links.filter(([path])=>path==='/settings'):links;
 return <AccountContext.Provider value={me.data}><a className="ieum-skip" href="#main-content">본문으로 건너뛰기</a><div className="ieum-shell"><aside className="ieum-nav"><div className="ieum-brand">IEUM</div><p className="ieum-kicker">PAPER TERMINAL / 1.1</p><p className="ieum-help">{me.data.workspace.name}</p><Button intent="ghost" aria-expanded={navOpen} onClick={()=>setNavOpen(!navOpen)}>메뉴 {navOpen?'접기':'펼치기'}</Button><nav className="ieum-product-navigation" data-open={navOpen} aria-label="개인 관리">{shownLinks.map(([to,label])=><NavLink key={to} to={to!} end={to==='/app'||to==='/settings'}>{label}</NavLink>)}{me.data.operator&&!me.data.requiresMfa&&<><hr className="ieum-rule"/><p className="ieum-kicker">INSTANCE OPERATIONS</p><NavLink to="/ops/users">회원 관리</NavLink><NavLink to="/ops/logs">운영 감사</NavLink><NavLink to="/ops/health">상태 · 백업</NavLink></>}</nav></aside><main id="main-content" className="ieum-main" tabIndex={-1}><header className="ieum-app-top"><div><Status>개인 공간</Status><p className="ieum-help">{me.data.user.name} · {me.data.user.email}</p></div><div className="ieum-cluster"><ThemeSelect/><Button intent="ghost" onClick={async()=>{try{await request('/api/auth/sign-out',{method:'POST',body:{}});q.clear();navigate('/login',{replace:true});}catch(e){setLogoutError(e);}}}>로그아웃</Button></div></header><ErrorMessage error={logoutError}/>{me.data.requiresMfa&&<Notice tone="warning">개인 자료에 접근하기 전에 2단계 인증을 등록해 주세요.</Notice>}<Outlet/><footer className="ieum-page-footer ieum-help">개인 기록은 비공개입니다. 검토한 버전만 Delivery API로 발행됩니다.</footer></main></div></AccountContext.Provider>;
}
const router=createBrowserRouter([{path:'/login',element:<Login/>},{element:<Shell/>,children:[{path:'/app',element:<Dashboard/>},{path:'/app/captures',element:<Captures/>},{path:'/app/captures/:id',element:<CaptureDetail/>},{path:'/app/tasks',element:<Tasks/>},{path:'/app/calendar',element:<Calendar/>},{path:'/app/contexts',element:<Contexts/>},{path:'/app/sources',element:<Sources/>},{path:'/app/wiki',element:<DocumentList wiki/>},{path:'/app/documents',element:<DocumentList/>},{path:'/app/documents/:id',element:<DocumentEditor/>},{path:'/app/documents/:id/publish',element:<PublishReview/>},{path:'/app/search',element:<Search/>},{path:'/app/proposals',element:<Proposals/>},{path:'/app/publications',element:<Publications/>},{path:'/app/delivery',element:<Delivery/>},{path:'/app/assets',element:<Assets/>},{path:'/app/data-transfer',element:<DataTransfer/>},{path:'/app/trash',element:<Trash/>},{path:'/app/jobs',element:<Jobs/>},{path:'/app/audit',element:<Audit/>},{path:'/app/notifications',element:<Notifications/>},{path:'/settings',element:<SecuritySettings/>},{path:'/settings/access',element:<Access/>},{path:'/ops/users',element:<Users/>},{path:'/ops/logs',element:<OperatorLogs/>},{path:'/ops/health',element:<Health/>}]},{path:'*',element:<Navigate to="/app" replace/>}]);
export function App(){return <ErrorBoundary><RouterProvider router={router}/></ErrorBoundary>;}
