import {useState,type ReactNode} from 'react';import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import {Button,Card,Field,Notice,Status,useTheme,Select} from '../../../../packages/ui/src';
import {request,textError,useAction,useBase,formatDate,str} from './api';import type {Row} from '../../../../packages/contracts/src';
export function ErrorMessage({error}:{error:unknown}){return error?<Notice tone="danger">{textError(error)}</Notice>:null;}
export function QueryState({isPending,error,children}:{isPending:boolean;error:unknown;children:ReactNode}){if(isPending)return <Notice>불러오는 중…</Notice>;if(error)return <ErrorMessage error={error}/>;return children;}
export function ThemeSelect(){const {preference,setPreference}=useTheme();return <Select label="화면 테마" value={preference} onChange={e=>setPreference(e.target.value as 'system'|'light'|'dark')}><option value="system">시스템 설정</option><option value="light">페이퍼 라이트</option><option value="dark">페이퍼 다크</option></Select>;}
export function Prose({body}:{body:string}){return <div className="ieum-prose"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span className="ieum-help">[외부 이미지: {alt??'이미지'} — 자동 로드하지 않음]</span>,a:({href,children})=><a href={href} rel="noreferrer noopener" target="_blank">{children}</a>}}>{body}</ReactMarkdown></div>;}
export function Reauth(){const [password,setPassword]=useState(''),[state,setState]=useState(''),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false);return <Card title="민감 작업 재확인"><form className="ieum-toolbar" onSubmit={async e=>{e.preventDefault();setError(null);setBusy(true);try{await request('/api/v1/me/reauthenticate',{method:'POST',body:{password}});setState('재확인되었습니다. 10분 동안 발행·키·내보내기를 진행할 수 있습니다.');setPassword('');}catch(err){setError(err);}finally{setBusy(false);}}}><Field label="현재 비밀번호" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" busy={busy}>재확인</Button></form>{state&&<Notice tone="success">{state}</Notice>}<ErrorMessage error={error}/></Card>;}
export function TrashButton({kind,id,onSuccess}:{kind:string;id:string;onSuccess?:()=>void}){const [confirm,setConfirm]=useState(false),a=useAction(),base=useBase();return <div className="ieum-stack-small">{confirm?<div className="ieum-cluster"><span>휴지통으로 이동할까요?</span><Button intent="danger" busy={a.isPending} onClick={()=>a.mutate({path:base+`/resources/${kind}/${id}/trash`,body:{}},{onSuccess:()=>onSuccess?.()})}>이동 확인</Button><Button onClick={()=>setConfirm(false)}>취소</Button></div>:<Button intent="ghost" onClick={()=>setConfirm(true)}>휴지통</Button>}<ErrorMessage error={a.error}/></div>;}
export function LogTable({items}:{items:Row[]}){return <div className="ieum-table-wrap"><table className="ieum-table"><caption>최근 변경 이력 — 본문과 비밀값은 기록하지 않습니다.</caption><thead><tr><th>시각</th><th>행동</th><th>대상</th></tr></thead><tbody>{items.map((r,i)=><tr key={str(r,'id')||str(r,'command_id')+i}><td>{formatDate(r.created_at)}</td><td>{str(r,'action')}</td><td><code className="ieum-inline-code">{str(r,'target_id')}</code></td></tr>)}</tbody></table></div>;}
