import {randomUUID,createHash} from 'node:crypto';
import {mkdir,writeFile,readFile,unlink} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {z} from 'zod';
import type {Database,Executor} from './db';import type {Principal} from './auth';
import {requireFresh} from './auth';
import {audit,command,readScoped,assertActor,fingerprint} from './commands';
import {invariant,requireValue,AppError} from './errors';import {captureInput,documentInput,uuid,timeZone} from '../../../packages/contracts/src';
import {createCaptureIn} from './personal';
const portable=z.object({format:z.literal('ieum-portable/v1'),captures:z.array(captureInput.omit({sourceId:true})).max(500).default([]),documents:z.array(documentInput).max(500).default([])}).strict();
const roots={capture:'capture',document:'document',task:'task',event:'calendar_event',source:'source',context:'context',asset:'asset'} as const;
export class OperationsService{
 private storage:string;
 constructor(private db:Database,assetDir:string){this.storage=resolve(assetDir);}
 private path(id:string){uuid.parse(id);return join(this.storage,id);}
 async preferences(actor:Principal){return requireValue((await this.db.query('SELECT theme,timezone AS time_zone,core_enabled,external_ai_allowed FROM user_preference WHERE user_id=$1',[actor.userId])).rows[0]);}
 async savePreferences(actor:Principal,value:unknown){const p=z.object({theme:z.enum(['system','light','dark']),timeZone,coreEnabled:z.boolean()}).strict().parse(value);await this.db.transaction(async tx=>{await tx.query('UPDATE user_preference SET theme=$1,timezone=$2,core_enabled=$3 WHERE user_id=$4',[p.theme,p.timeZone,p.coreEnabled,actor.userId]);await tx.query("INSERT INTO instance_audit_event(id,actor_id,action,target_id) VALUES($1,$2,'PREFERENCES_UPDATED',$2)",[randomUUID(),actor.userId]);});return {saved:true};}
 assets(actor:Principal){return readScoped(this.db,actor,async tx=>({items:(await tx.query('SELECT id,name,media_type,size_bytes,checksum,state,created_at FROM asset WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 100')).rows}));}
 async uploadText(actor:Principal,value:unknown){const p=z.object({name:z.string().trim().min(1).max(200),text:z.string().max(1048576),mediaType:z.enum(['text/plain','text/markdown'])}).strict().parse(value);const data=Buffer.from(p.text,'utf8');invariant(data.length<=1048576&&!p.text.includes('\0'),'INVALID_FILE','UTF-8 텍스트 파일은 1 MiB 이하여야 합니다.');
  const id=randomUUID(),storageKey=randomUUID(),checksum=createHash('sha256').update(data).digest('hex');await mkdir(this.storage,{recursive:true,mode:0o700});await writeFile(this.path(storageKey),data,{flag:'wx',mode:0o600});
  try{await readScoped(this.db,actor,async tx=>{const total=(await tx.query<{n:string}>('SELECT COALESCE(sum(size_bytes),0) AS n FROM asset WHERE deleted_at IS NULL')).rows[0]!.n;invariant(Number(total)+data.length<=104857600,'QUOTA_EXCEEDED','텍스트 자료 용량 100 MiB를 초과했습니다.',413);await tx.query('INSERT INTO asset(id,workspace_id,name,media_type,size_bytes,checksum,storage_key) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,actor.workspaceId,p.name,p.mediaType,data.length,checksum,storageKey]);await audit(tx,actor,'ASSET_STORED','asset',id,1,randomUUID());});}catch(e){await unlink(this.path(storageKey)).catch(()=>{});throw e;}return {id,checksum};
 }
 async downloadAsset(actor:Principal,id:string){uuid.parse(id);return readScoped(this.db,actor,async tx=>{const a=requireValue((await tx.query<{name:string;storage_key:string;checksum:string}>('SELECT name,storage_key,checksum FROM asset WHERE id=$1 AND deleted_at IS NULL AND state=\'VERIFIED\'',[id])).rows[0]);const data=await readFile(this.path(a.storage_key));invariant(createHash('sha256').update(data).digest('hex')===a.checksum,'FILE_INTEGRITY','파일 무결성을 확인할 수 없습니다.',503);return {name:a.name,data};});}
 trash(actor:Principal){return readScoped(this.db,actor,async tx=>({items:(await tx.query(`SELECT id,title,kind,deleted_at FROM (SELECT id,title,'capture' AS kind,deleted_at FROM capture UNION ALL SELECT id,title,'document',deleted_at FROM document UNION ALL SELECT id,title,'task',deleted_at FROM task UNION ALL SELECT id,title,'event',deleted_at FROM calendar_event UNION ALL SELECT id,title,'source',deleted_at FROM source UNION ALL SELECT id,name,'context',deleted_at FROM context UNION ALL SELECT id,name,'asset',deleted_at FROM asset) r WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC LIMIT 200`)).rows}));}
 deleteOrRestore(actor:Principal,kind:string,id:string,restore:boolean,key:unknown){const k=z.enum(['capture','document','task','event','source','context','asset']).parse(kind);uuid.parse(id);return command(this.db,actor,'data.'+(restore?'restore':'trash'),key,{kind:k,id},async(tx,cid)=>{
  const table=roots[k];requireValue((await tx.query(`SELECT id FROM ${table} WHERE id=$1 FOR UPDATE`,[id])).rows[0]);
  if(k==='document'&&!restore)invariant(!(await tx.query("SELECT id FROM publication WHERE document_id=$1 AND status='PUBLISHED'",[id])).rows.length,'WITHDRAW_FIRST','공개된 문서는 먼저 발행을 철회해 주세요.',409);
  await tx.query(`UPDATE ${table} SET deleted_at=${restore?'NULL':'now()'}${k==='asset'?`,state='${restore?'VERIFIED':'TRASHED'}'`:''} WHERE id=$1`,[id]);
  if(!restore&&(k==='capture'||k==='context'))await tx.query(`UPDATE proposal SET state='STALE' WHERE ${k==='capture'?'capture_id':'context_id'}=$1 AND state='PENDING'`,[id]);
  await audit(tx,actor,restore?'RESOURCE_RESTORED':'RESOURCE_TRASHED',k,id,null,cid);return {id,restored:restore};
 });}
 async previewImport(actor:Principal,value:unknown){const p=portable.parse(value);invariant(p.captures.length+p.documents.length>0,'EMPTY_IMPORT','가져올 기록 또는 문서가 필요합니다.');const id=randomUUID(),hash=fingerprint(p);return readScoped(this.db,actor,async tx=>{await tx.query('INSERT INTO data_transfer(id,workspace_id,actor_id,manifest_hash,payload) VALUES($1,$2,$3,$4,$5::jsonb)',[id,actor.workspaceId,actor.userId,hash,JSON.stringify(p)]);return {id,manifestHash:hash,captures:p.captures.length,documents:p.documents.length,policy:'새 ID로 생성합니다. 연결·과거 버전·발행 상태는 가져오지 않습니다.'};});}
 applyImport(actor:Principal,id:string,value:unknown,key:unknown){uuid.parse(id);const p=z.object({manifestHash:z.string().length(64)}).strict().parse(value);return command(this.db,actor,'import.apply',key,{id,...p},async(tx,cid)=>{
  const r=requireValue((await tx.query<{state:string;manifest_hash:string;payload:unknown;created_at:Date}>('SELECT state,manifest_hash,payload,created_at FROM data_transfer WHERE id=$1 FOR UPDATE',[id])).rows[0]);invariant(r.state==='PREVIEW'&&r.manifest_hash===p.manifestHash&&Date.now()-new Date(r.created_at).getTime()<3600000,'IMPORT_STALE','미리보기가 만료되었거나 달라졌습니다.',409);const data=portable.parse(r.payload);invariant(fingerprint(data)===p.manifestHash,'IMPORT_CHANGED','가져오기 자료가 변경되었습니다.',409);
  for(const c of data.captures)await createCaptureIn(tx,actor,c);
  for(const d of data.documents){const docId=randomUUID();await tx.query('INSERT INTO document(id,workspace_id,kind,title,created_by) VALUES($1,$2,$3,$4,$5)',[docId,actor.workspaceId,d.kind,d.title,actor.userId]);await tx.query("INSERT INTO document_draft(workspace_id,document_id,title,body,public_meta) VALUES($1,$2,$3,$4,'null'::jsonb)",[actor.workspaceId,docId,d.title,d.body]);}
  await tx.query("UPDATE data_transfer SET state='APPLIED',applied_at=now() WHERE id=$1",[id]);await audit(tx,actor,'IMPORT_APPLIED','data_transfer',id,null,cid);return {imported:data.captures.length+data.documents.length};
 });}
 jobs(actor:Principal){return readScoped(this.db,actor,async tx=>({items:(await tx.query('SELECT id,kind,state,attempt,error_code,created_at,updated_at FROM job ORDER BY created_at DESC LIMIT 100')).rows}));}
 async enqueueExport(actor:Principal,key:unknown){await requireFresh(this.db,actor);return command(this.db,actor,'export.enqueue',key,{},async(tx,cid)=>{const id=randomUUID();await tx.query("INSERT INTO job(id,workspace_id,actor_id,kind) VALUES($1,$2,$3,'EXPORT')",[id,actor.workspaceId,actor.userId]);await audit(tx,actor,'EXPORT_REQUESTED','job',id,null,cid);return {id,state:'QUEUED'};});}
 jobAction(actor:Principal,id:string,value:unknown,key:unknown){uuid.parse(id);const p=z.object({action:z.enum(['RETRY','CANCEL'])}).strict().parse(value);return command(this.db,actor,'job.action',key,{id,...p},async(tx,cid)=>{const row=requireValue((await tx.query<{state:string;attempt:number}>('SELECT state,attempt FROM job WHERE id=$1 FOR UPDATE',[id])).rows[0]);invariant(p.action==='RETRY'?['FAILED','CANCELED'].includes(row.state):['QUEUED','RUNNING'].includes(row.state),'INVALID_JOB_STATE','현재 상태에서 실행할 수 없습니다.',409);invariant(row.attempt<5||p.action==='CANCEL','ATTEMPT_LIMIT','재시도 한도를 초과했습니다.',409);await tx.query('UPDATE job SET state=$1,lease_token=NULL,lease_until=NULL,error_code=NULL,updated_at=now() WHERE id=$2',[p.action==='RETRY'?'QUEUED':'CANCELED',id]);await audit(tx,actor,'JOB_'+p.action,'job',id,null,cid);return {updated:true};});}
 async downloadExport(actor:Principal,id:string){uuid.parse(id);await requireFresh(this.db,actor);return readScoped(this.db,actor,async tx=>{const j=requireValue((await tx.query<{result_key:string;updated_at:Date}>("SELECT result_key,updated_at FROM job WHERE id=$1 AND kind='EXPORT' AND state='SUCCEEDED'",[id])).rows[0]);invariant(Date.now()-new Date(j.updated_at).getTime()<86400000,'EXPORT_EXPIRED','내보내기 다운로드가 만료되었습니다.',410);return readFile(this.path(j.result_key));});}
 auditLog(actor:Principal){return readScoped(this.db,actor,async tx=>({items:(await tx.query('SELECT action,target_type,target_id,version,created_at,command_id FROM audit_event ORDER BY created_at DESC,id LIMIT 200')).rows}));}
 async notifications(actor:Principal){return readScoped(this.db,actor,async tx=>({items:(await tx.query('SELECT id,title,job_id,read_at,created_at FROM notification WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[actor.userId])).rows}));}
 markRead(actor:Principal,id:string,key:unknown){uuid.parse(id);return command(this.db,actor,'notification.read',key,{id},async tx=>{await tx.query('UPDATE notification SET read_at=now() WHERE id=$1 AND user_id=$2',[id,actor.userId]);return {read:true};});}
 async operatorUsers(actor:Principal){invariant(actor.operator,'FORBIDDEN','운영자 권한이 필요합니다.',403);return {items:(await this.db.query('SELECT u.id,u.name,u.email,u.status,u.two_factor_enabled,u.created_at,EXISTS(SELECT 1 FROM instance_operator o WHERE o.user_id=u.id) AS operator FROM auth_user u ORDER BY u.created_at DESC LIMIT 100')).rows};}
 async setUserStatus(actor:Principal,id:string,value:unknown){invariant(actor.operator,'FORBIDDEN','운영자 권한이 필요합니다.',403);await requireFresh(this.db,actor);const p=z.object({status:z.enum(['ACTIVE','SUSPENDED'])}).strict().parse(value);return this.db.transaction(async tx=>{
  await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['actor:'+id]);const target=requireValue((await tx.query<{id:string}>('SELECT id FROM auth_user WHERE id=$1 FOR UPDATE',[id])).rows[0]);invariant(target.id!==actor.userId,'SELF_SUSPEND','자신의 운영 계정은 여기서 정지할 수 없습니다.',409);invariant(!(await tx.query('SELECT user_id FROM instance_operator WHERE user_id=$1',[id])).rows.length,'OPERATOR_PROTECTED','운영자 변경은 별도 운영 절차를 이용해 주세요.',409);
  await tx.query('UPDATE auth_user SET status=$1 WHERE id=$2',[p.status,id]);if(p.status==='SUSPENDED'){await tx.query('DELETE FROM auth_session WHERE user_id=$1',[id]);const ws=(await tx.query<{workspace_id:string}>('SELECT workspace_id FROM workspace_member WHERE user_id=$1',[id])).rows[0];if(ws){await tx.query('SET LOCAL ROLE ieum_scoped');await tx.query("SELECT set_config('ieum.workspace_id',$1,true)",[ws.workspace_id]);await tx.query('UPDATE delivery_key SET revoked_at=now()');await tx.query('RESET ROLE');}}
  await tx.query('INSERT INTO instance_audit_event(id,actor_id,action,target_id) VALUES($1,$2,$3,$4)',[randomUUID(),actor.userId,'USER_'+p.status,id]);return {status:p.status};
 });}
 async operatorLogs(actor:Principal){invariant(actor.operator,'FORBIDDEN','운영자 권한이 필요합니다.',403);return {items:(await this.db.query('SELECT id,action,target_id,created_at FROM instance_audit_event ORDER BY created_at DESC LIMIT 200')).rows};}
 async health(actor:Principal){invariant(actor.operator,'FORBIDDEN','운영자 권한이 필요합니다.',403);await this.db.query('SELECT 1');return {database:'ready',engine:this.db.kind,model:'not-configured',backups:'external-runbook-required',jobs:(await this.db.query('SELECT state,count(*)::int AS count FROM job GROUP BY state')).rows};}
 /** Claims one persisted job. Durable row + attempt token fence both duplicate workers and stale completion. */
 async runOne(){
  const selected=(await this.db.query<{id:string;workspace_id:string;actor_id:string}>("SELECT id,workspace_id,actor_id FROM job WHERE (state='QUEUED' OR (state='RUNNING' AND lease_until<now())) AND attempt<5 ORDER BY created_at LIMIT 1")).rows[0];if(!selected)return false;
  const actor:Principal={userId:selected.actor_id,workspaceId:selected.workspace_id,sessionId:'worker',operator:false,twoFactorEnabled:true};const token=randomUUID();let resultKey:string|undefined;
  try{
   const claimed=await readScoped(this.db,actor,async tx=>{const r=(await tx.query<{attempt:number}>("UPDATE job SET state='RUNNING',attempt=attempt+1,lease_token=$1,lease_until=now()+interval '2 minutes',updated_at=now() WHERE id=$2 AND (state='QUEUED' OR (state='RUNNING' AND lease_until<now())) AND attempt<5 RETURNING attempt",[token,selected.id])).rows[0];if(!r)return false;await tx.query("INSERT INTO job_attempt(workspace_id,job_id,attempt,lease_token,state) VALUES($1,$2,$3,$4,'RUNNING')",[actor.workspaceId,selected.id,r.attempt,token]);return true;});if(!claimed)return false;
   const snapshot=await readScoped(this.db,actor,async tx=>{
    const captures=(await tx.query("SELECT c.title,c.kind,r.body,'[]'::jsonb AS tags FROM capture c JOIN capture_revision r ON r.workspace_id=c.workspace_id AND r.capture_id=c.id AND r.revision=c.version WHERE c.deleted_at IS NULL ORDER BY c.id LIMIT 501")).rows;
    const documents=(await tx.query('SELECT f.title,d.kind,f.body FROM document d JOIN document_draft f ON f.workspace_id=d.workspace_id AND f.document_id=d.id WHERE d.deleted_at IS NULL ORDER BY d.id LIMIT 501')).rows;
    invariant(captures.length<=500&&documents.length<=500,'EXPORT_LIMIT','현재 이식 형식은 기록/문서 각각 500개까지 지원합니다.');
    return {format:'ieum-portable/v1',captures,documents};
   });resultKey=randomUUID();await mkdir(this.storage,{recursive:true,mode:0o700});await writeFile(this.path(resultKey),JSON.stringify(snapshot,null,2),{flag:'wx',mode:0o600});const file=resultKey;
   const applied=await readScoped(this.db,actor,async tx=>{const r=await tx.query("UPDATE job SET state='SUCCEEDED',result_key=$1,lease_until=NULL,updated_at=now() WHERE id=$2 AND state='RUNNING' AND lease_token=$3 AND lease_until>now() RETURNING id",[file,selected.id,token]);if(!r.rows.length)return false;await tx.query("UPDATE job_attempt SET state='SUCCEEDED',finished_at=now() WHERE job_id=$1 AND lease_token=$2",[selected.id,token]);await tx.query('INSERT INTO notification(id,workspace_id,user_id,title,job_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(job_id,user_id) DO NOTHING',[randomUUID(),actor.workspaceId,actor.userId,'기록·문서 내보내기가 완료되었습니다.',selected.id]);return true;});if(!applied)await unlink(this.path(file)).catch(()=>{});
  }catch(e){if(resultKey)await unlink(this.path(resultKey)).catch(()=>{});await this.db.scoped(actor.workspaceId,actor.userId,async tx=>{await tx.query("UPDATE job SET state='FAILED',error_code=$1,lease_until=NULL,updated_at=now() WHERE id=$2 AND state='RUNNING' AND lease_token=$3",[e instanceof AppError?e.code:'JOB_FAILED',selected.id,token]);await tx.query("UPDATE job_attempt SET state='FAILED',error_code=$1,finished_at=now() WHERE job_id=$2 AND lease_token=$3",[e instanceof AppError?e.code:'JOB_FAILED',selected.id,token]);}).catch(()=>{});}
  return true;
 }
}
