import {useState} from 'react';import {useQueryClient} from '@tanstack/react-query';import {useNavigate,useSearchParams} from 'react-router-dom';
import {Button,Card,Field,Page,Notice,Status,Select,Check} from '../../../../packages/ui/src';
import {request,textError,useAccount,useData,useAction,str,formatDate} from '../shared/api';import {ErrorMessage,ThemeSelect,Reauth,QueryState} from '../shared/components';import type {Row} from '../../../../packages/contracts/src';
export function Login(){const [params]=useSearchParams();const [mode,setMode]=useState(params.has('invite')?'invite':'login'),[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[token,setToken]=useState(params.get('invite')??''),[backup,setBackup]=useState(false),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const q=useQueryClient(),navigate=useNavigate();
 async function submit(){setBusy(true);setError(null);try{if(mode==='invite'){await request('/api/v1/invitations/accept',{method:'POST',body:{token,email,name,password}});setMode('login');setPassword('');setMessage('초대를 수락했습니다. 새 개인 공간으로 로그인해 주세요.');return;}
  const r=await request(mode==='mfa'?'/api/auth/two-factor/'+(backup?'verify-backup-code':'verify-totp'):'/api/auth/sign-in/email',{method:'POST',body:mode==='mfa'?{code,trustDevice:false}:{email,password}});
  if(r.twoFactorRedirect){setMode('mfa');setPassword('');return;}await q.invalidateQueries({queryKey:['me']});navigate('/app',{replace:true});
 }catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="ieum-auth-page"><div className="ieum-auth ieum-stack"><header><p className="ieum-kicker">YOUR PRIVATE WORKSPACE</p><h1 className="ieum-brand">IEUM / 이음</h1><p>기록에서 행동으로, 경험에서 통찰로.</p></header><ThemeSelect/><Card title={mode==='invite'?'초대 수락 · 개인 공간 만들기':mode==='mfa'?'2단계 인증':'로그인'}><form className="ieum-stack" onSubmit={e=>{e.preventDefault();void submit();}}>{mode==='mfa'?<><Field label={backup?'일회용 복구 코드':'인증 앱 코드'} value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" required/><Check label="복구 코드로 인증" checked={backup} onChange={e=>setBackup(e.target.checked)}/></>:<>{mode==='invite'&&<><Field label="초대 토큰" value={token} onChange={e=>setToken(e.target.value)} required/><Field label="이름" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></>}<Field label="이메일" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/><Field label="비밀번호" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='invite'?'new-password':'current-password'} minLength={mode==='invite'?15:1} required/></>}{message&&<Notice>{message}</Notice>}<ErrorMessage error={error}/><Button intent="primary" type="submit" busy={busy}>{mode==='invite'?'개인 공간 만들기':mode==='mfa'?'인증 완료':'로그인'}</Button></form><div className="ieum-cluster"><Button intent="ghost" onClick={()=>{setMode(mode==='invite'?'login':'invite');setError(null);}}> {mode==='invite'?'로그인으로':'초대받았나요?'}</Button><Button intent="ghost" onClick={()=>setMessage('메일 복구는 운영자가 메일 어댑터를 설정한 경우 지원합니다. 미설정 인스턴스는 서버의 account-recovery 절차를 사용하세요.')}>계정 복구 안내</Button></div></Card><p className="ieum-help">공개 회원가입 없음 · 개인 공간은 다른 회원과 공유되지 않습니다.</p></div></div>;
}
export function SecuritySettings(){const me=useAccount(),q=useQueryClient();const pref=useData<Row>('/api/v1/me/preferences'),sessions=useData<{items:Row[]}>('/api/v1/me/sessions');const action=useAction();const [password,setPassword]=useState(''),[code,setCode]=useState(''),[setup,setSetup]=useState<Row|null>(null),[message,setMessage]=useState(''),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false);
 async function mfa(path:string,body:unknown){setBusy(true);setError(null);try{const r=await request('/api/auth/two-factor/'+path,{method:'POST',body});if(path==='enable')setSetup(r);else{setMessage('2단계 인증이 확인되었습니다. 복구 코드를 안전하게 보관해 주세요.');await q.invalidateQueries({queryKey:['me']});}setPassword('');}catch(e){setError(e);}finally{setBusy(false);}}
 return <Page title="설정 · 보안" eyebrow="PRIVATE SETTINGS"><Card title="표시 환경"><ThemeSelect/><QueryState isPending={pref.isPending} error={pref.error}>{pref.data&&<><p>서버 시간대: {str(pref.data,'time_zone')}</p><Check label="기록 정리 보조 사용 (lexical baseline)" checked={Boolean(pref.data.core_enabled)} onChange={e=>action.mutate({path:'/api/v1/me/preferences',method:'PUT',body:{theme:str(pref.data!,'theme'),timeZone:str(pref.data!,'time_zone'),coreEnabled:e.target.checked}})}/><Notice>외부 AI 전송은 비활성입니다. 테마 선택은 기기에만 저장되며 기록 본문은 저장하지 않습니다.</Notice></>}</QueryState></Card><Card title="2단계 인증"><Status tone={me.user.twoFactorEnabled?'success':'warning'}>{me.user.twoFactorEnabled?'등록됨':'등록 필요'}</Status>{!me.user.twoFactorEnabled&&<><Field label="현재 비밀번호 (인증 설정용)" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><Button busy={busy} onClick={()=>void mfa('enable',{password})}>인증 앱 등록 준비</Button></>}{setup&&<><Field label="인증 앱에 입력할 URI" readOnly value={str(setup,'totpURI')}/><Notice tone="warning">인증 앱에서 URI의 secret 값을 등록하세요. 아래 복구 코드는 한 번만 표시됩니다.</Notice><pre className="ieum-break">{Array.isArray(setup.backupCodes)?setup.backupCodes.join('\n'):''}</pre><Field label="등록 확인 코드" value={code} autoComplete="one-time-code" onChange={e=>setCode(e.target.value)}/><Button intent="primary" busy={busy} onClick={()=>void mfa('verify-totp',{code,trustDevice:false})}>코드 확인</Button></>}{message&&<Notice tone="success">{message}</Notice>}<ErrorMessage error={error}/></Card><Reauth/><Card title="접속 기기"><QueryState isPending={sessions.isPending} error={sessions.error}><ul className="ieum-list">{sessions.data?.items.map(s=><li className="ieum-list-item" key={str(s,'id')}><div><strong>{s.current?'현재 세션':'다른 세션'}</strong><p className="ieum-help">{str(s,'user_agent')||'기기 정보 없음'}</p><p>{formatDate(s.created_at)}</p></div><Button busy={action.isPending} onClick={()=>action.mutate({path:'/api/v1/me/sessions/'+str(s,'id')+'/revoke',body:{}},{onSuccess:async()=>{await q.invalidateQueries({queryKey:['me']});}})}>세션 해제</Button></li>)}</ul></QueryState><ErrorMessage error={action.error}/></Card></Page>;
}
